### PR TITLE
Logging

### PR DESCRIPTION
**Pull request by brucexi999**
Hi Ian,

I see that you implemented the tests for other modules using pytest while I did the testing for the logger using unittest. I don't think this will have an impact on the functionality of the logger or the effectiveness of the tests. But I am happy to switch to pytest if you prefer that way.

I can also help if you want documentation regarding the use of the logger.

Thanks for taking the time to review!
Bruce

### CODE REVIEW

**Comment by ianrmhill** [comment]
Looking pretty good Bruce! I think a couple things we want to clean up before merging:
-There's a bunch of pycache files and a few small formatting changes that are included in the change, we want to remove those (maybe add .gitignore catches for those pycache file types if not there already)
-I'm not huge on the design decision of defining a helper function within the simulate function, is it possible to move that logging handler routine to helpers.py as well?
-There's a few typos in the documentation/comments for the main changes, and some code formatting issues to lint out
-I can handle moving the tests to pytest instead of unittest

**Comment by ianrmhill** [comment]
Also: this PR will partially resolve #12

**Comment by brucexi999** [comment]
Thanks for the feedback Ian, I will start working on the improvements. 
Task 2: yes I think it's doable, you might have to import that function from helpers.py as well, just like how we deal with the logger itself. It can take the default logger, logging level, and handlers as arguments, and return the configured logger to the `simulate` function
Task 3: I might need your help to specify the correct code formatting

**Comment by ianrmhill** [comment]
Linting checks have nothing to do with the PR, will fix/waive those in separate PR, merged!

**Pull request merged**
